export class CampusHubSurveyModel {
  constructor(
      public name: Array<Object>,
      public phoneNumber: Array<Object>,
      public email: Array<Object>,
      public frequency: Array<Object>,
      public regularFruitJuice: Array<Object>,
      public mixedFruitJuice: Array<Object>,
      public iceCreamShakes: Array<Object>,
      public milkShakes: Array<Object>,
      public fruitMilkShakes: Array<Object>,
      public desserts: Array<Object>,
      public iceCreamFlavours: Array<Object>,
      public hotBeverages: Array<Object>,
      public coldBeverages: Array<Object>,
      public quickBites: Array<Object>,
      public miniMeals: Array<Object>,
      public paranthas: Array<Object>,
      public riceMeals: Array<Object>,
      public maggi: Array<Object>,
      public chaat: Array<Object>,
      public chinese: Array<Object>,
      public extras: Array<Object>,
      public sandwich: Array<Object>,
      public frankie: Array<Object>,
      public hygieneOfItems: Array<Object>,
      public absenceMenuItemTimes: Array<Object>,
      public otherParameters: Array<Object>,
      public otherSuggestions?: Array<Object>
  ) { }
}
