export class BrewAndBitesSurveyModel {
  constructor(
      public name: Array<Object>,
      public phoneNumber: Array<Object>,
      public email: Array<Object>,
      public frequency: Array<Object>,
      public vegStarters: Array<Object>,
      public nonVegStarters: Array<Object>,
      public regularCoffee: Array<Object>,
      public blackCoffee: Array<Object>,
      public milkshakes: Array<Object>,
      public sundaes: Array<Object>,
      public nonVegPizzas: Array<Object>,
      public vegPizzas: Array<Object>,
      public sandwiches: Array<Object>,
      public paninis: Array<Object>,
      public wraps: Array<Object>,
      public pastas: Array<Object>,
      public burgers: Array<Object>,
      public extraToppingsOrDips: Array<Object>,
      public regularTea: Array<Object>,
      public greenTea: Array<Object>,
      public infusionTea: Array<Object>,
      public mojito: Array<Object>,
      public slush: Array<Object>,
      public iceTea: Array<Object>,
      public frappe: Array<Object>,
      public brewtastic: Array<Object>,
      public onTheRocks: Array<Object>,
      public hygieneOfItems: Array<Object>,
      public absenceMenuItemTimes: Array<Object>,
      public otherParameters: Array<Object>,
      public otherSuggestions?: Array<Object>
  ) { }
}
