export class CanteensSurveyModel {
  constructor(
      public name: Array<Object>,
      public phoneNumber: Array<Object>,
      public email: Array<Object>,
      public hostel: Array<Object>,
      public frequency: Array<Object>,
      public teaCoffee: Array<Object>,
      public milkshakes: Array<Object>,
      public juice: Array<Object>,
      public paratha: Array<Object>,
      public franky: Array<Object> ,
      public eggItems: Array<Object>,
      public riceAndNoodles: Array<Object>,
      public rice: Array<Object>,
      public dryChickenAndPaneer: Array<Object>,
      public sandwich: Array<Object>,
      public dryBhaji: Array<Object>,
      public vegAndPaneerGravy: Array<Object>,
      public nonVeg: Array<Object>,
      public dal: Array<Object>,
      public maggi: Array<Object>,
      public soups: Array<Object>,
      public dosa: Array<Object>,
      public extras: Array<Object>,      
      public hygieneOfItems: Array<Object>,
      public absenceMenuItemTimes: Array<Object>,
      public otherParameters: Array<Object>,
      public otherSuggestions?: Array<Object>
  ) { }
}